### ISSUE TITLE
Make this style of event easier to do! 

### ISSUE THREAD

**Issue by JosephMcArthur** [sparcopen/open-research-doathon#47]
[//]: # "=======================
Instructions for posting issues: 
(1) Write your post (below this text blob) using Markdown (as per https://guides.github.com/features/mastering-markdown/ ) or just plain text.
(2) Add the appropriate labels to your post, e.g. 'idea' or 'lightning talk' (or both for idea pitches), 'interests', 'skills' or 'experience'. Use 'help wanted' as needed.
(3) Don't worry about these introductory lines - you can leave or delete them, as they won't display anyway (you can check this via Preview).
(4) Hit the 'Submit new issue' button.
============================"

We'd like to make it easier to do this type of event:
* participatory program
* remote involvement
* low "overhead" programming

easier. We figure we can just document the repo then people can fork it for their own events!

**Comment by goodwingibbins** [comment]
Note of importance: a simple "welcome to github" needs to go along with the forkable repo

**Comment by fionabradley** [comment]
There were so many good discussions going on at the same time and I wanted to join them all! Maybe 60 minute chunks so people can rotate around each hour and those who are working intensely on something can continue on the same thing all afternoon and have new people join them on the hour. This might be handy also for those joining remotely, "join at 4pm to discuss x'

**Comment by JosephMcArthur** [comment]
I think @Daniel-Mietchen has also tried to make sure this event is aware of it's history & builds on others work. We could put this in the pack too I think.

**Comment by npscience** [comment]
Suggestions: Up the XX:XY ratio, e.g. come-along-with-a-friend style strategies

**Comment by goodwingibbins** [comment]
Trying to follow remotely - awesome to see all the great work and hello everyone from the Alps! 

One suggestion: every lighting lecture could have a 1-2 word unique identifier? Especially for someone not hacking/doing full-time, the #XX can extra processing. I'd suggest: "#XX (Identity Words)" was used where possible.

**Comment by Daniel-Mietchen** [comment]
@JosephMcArthur We have to move the hat rack files into another repo if we want to keep this one CC0.

**Comment by Daniel-Mietchen** [comment]
Another one to add: - perhaps ask people how/where they got to know about the event.

**Comment by Daniel-Mietchen** [comment]
The event documentation is gradually moving over to https://github.com/sparcopen/open-research-doathon/tree/master/Do-a-thon%20template%20files .

**Comment by Daniel-Mietchen** [comment]
A related Wikimania submission: https://wikimania2017.wikimedia.org/wiki/Submissions/How_to_make_successful_hackathon

**Comment by JosephMcArthur** [comment]
By the end of the Mozilla Sprint:

- [x] clone this repo
- [ ] have a landing page to advertise these styles of events 
- [ ] Finish preparation.md
- [ ] finish on the day instructions
- [ ] finish giant_shoulder.md
- [ ] finish what is a do-a-thon.md
- [x] set up domains to be https
- [ ] turn meta-tags into checklist
- [ ] reveiw contributing / issue_template / readme etc for their use in cloned repo
- [ ] give follow up strategy that uses github & can be done on the day

**Comment by JosephMcArthur** [comment]
@Daniel-Mietchen I've set up a clone here: https://github.com/sparcopen/do-a-doathon & the site here: http://doathon.org/. At time of writing, that domain worked, however I've done some work to try and route the domain via a free cloudflare account to enable custom domains & https (the only way to do that).

**Comment by npscience** [comment]
Can we include this as a strategy for getting things done / engaging contributors on the next opencon collaborate call?

**Comment by JosephMcArthur** [comment]
If you're keen, I'm sure we can figure something out! 

Note, https://doathon.org/ now works. \o/ \o/ \o/ \o/ \o/. Gotta say, it was pretty trival to figure out this workaround, I'm slightly worried things don't look as good as they seem.

**Comment by npscience** [comment]
Hoorah for getting it working \o/

**Comment by JosephMcArthur** [comment]
Have moved above to-do's to the new repo here: https://github.com/sparcopen/do-a-doathon/issues.

**Comment by JosephMcArthur** [comment]
I'm actually going to close this now... just for tidyness.
